Content:
    - framework/doc/content
    - modules/peridynamics/doc/content

Renderer:
    type: MooseDocs.base.MaterializeRenderer
    name: MOOSE Peridynamics Module
    repo: https://github.com/idaholab/moose
    home: /documentation/modules/peridynamics

Extensions:
    appsyntax:
        type: MooseDocs.extensions.appsyntax
        executable: ${MOOSE_DIR}/modules/peridynamics
        hide:
            framework: !include framework/doc/hidden.yml
            phase_field: !include modules/peridynamics/doc/hidden.yml
        remove: !include framework/doc/remove.yml
        includes:
            - framework/include
            - modules/peridynamics/include
    globals:
        type: MooseDocs.extensions.panoptic
        shortcuts: !include framework/doc/globals.yml
    acronyms:
        type: MooseDocs.extensions.acronym
        acronyms: !include framework/doc/acronyms.yml
