reader: moosedown.base.readers.MarkdownReader
renderer: moosedown.base.MaterializeRenderer
translator: moosedown.base.Translator
extensions:
    - moosedown.extensions.core
    - moosedown.extensions.command
    - moosedown.extensions.devel
    - moosedown.extensions.floats
    - moosedown.extensions.include

pages:
    framework:
       root_dir: docs/content
       content:
           - utilities/moosedown/*
           - contrib/**
           - css/*
           - js/*
