Content:
    general:
        root_dir: docs/content
        content:
            #- utilities/MooseDocs/**
            - media/**
            - contrib/**
            - css/*
            - js/*
    framework:
        root_dir: framework/doc/content
    levelset:
        root_dir: modules/level_set/doc/content

Reader:
    type: MooseDocs.base.MarkdownReader

Renderer:
    type: MooseDocs.base.MaterializeRenderer
    repo: https://github.com/idaholab/moose
    name: MOOSE LevelSet Module
    home: http://mooseframework.org/moose

Extensions:
    appsyntax:
        type: MooseDocs.extensions.appsyntax
        executable: ${MOOSE_DIR}/modules/level_set
        includes:
            - framework/include
    globals:
        type: MooseDocs.extensions.global
        shortcuts: !include ../../../docs/globals.yml
