Content:
    workshop:
        root_dir: ${MOOSE_DIR}/tutorials/tutorial02_multiapps/doc/content
    moose:
        root_dir: ${MOOSE_DIR}/framework/doc/content
        content:
            - large_media/testing/*
            - contrib/**
            - css/**
            - js/**
            - bib/**
    large_media:
        root_dir: ${MOOSE_DIR}/large_media

Renderer:
    type: MooseDocs.base.RevealRenderer
    theme: simple

Extensions:
    disable_defaults: True
    MooseDocs.extensions.comment: default
    MooseDocs.extensions.command: default
    MooseDocs.extensions.core: default
    MooseDocs.extensions.config: default
    MooseDocs.extensions.media: default
    MooseDocs.extensions.floats: default
    MooseDocs.extensions.include: default
    MooseDocs.extensions.bibtex: default
    MooseDocs.extensions.katex:
        macros:
            \vec: "\\bar" # TODO: \vec doesn't render
            \pf: "\\frac{\\partial #1}{\\partial #2}"
    MooseDocs.extensions.style: default
    MooseDocs.extensions.autolink: default
    MooseDocs.extensions.materialicon: default
    MooseDocs.extensions.heading: default
    MooseDocs.extensions.table: default
    MooseDocs.extensions.layout: default
    MooseDocs.extensions.content: default
    MooseDocs.extensions.modal: default
    MooseDocs.extensions.acronym:
        acronyms: !include framework/doc/acronyms.yml
    MooseDocs.extensions.listing:
        modal-link: False
    MooseDocs.extensions.reveal: default
