Content:
    general:
        root_dir: docs/content
        content:
            - utilities/MooseDocs/**
            - media/**
            - contrib/**
            - css/*
            - js/*
    framework:
        root_dir: framework/doc/content
        content:
            - documentation/systems/**

Reader:
    type: MooseDocs.base.MarkdownReader

Renderer:
    type: MooseDocs.base.MaterializeRenderer
    repo: https://github.com/idaholab/moose
    name: MOOSE
    home: http://mooseframework.org/moose
    navigation:
        Getting Started:
            Mac OS: docs/content/getting_started/installation/mac_os.md
            Ubuntu: docs/content/getting_started/installation/ubuntu.md
            Mint: docs/content/getting_started/installation/mint.md
            OpenSUSE: docs/content/getting_started/installation/opensuse.md
            Fedora: docs/content/getting_started/installation/fedora.md
            CentOS: docs/content/getting_started/installation/centos.md
            Windows 10: docs/content/getting_started/installation/windows10.md
            HPC Cluster: docs/content/getting_started/installation/cluster.md
            Manual Install: docs/content/getting_started/installation/manual_installation.md
        Documentation:
            Systems: docs/content/documentation/systems/index.md
            Application Development: docs/content/documentation/application_development/index.md
            Interfaces: docs/content/documentation/interfaces/index.md
            Modules: docs/content/documentation/modules/index.md
            MooseUtils: docs/content/documentation/MooseUtils/index.md
            Software Quality: docs/content/documentation/sqa/index.md
        Utilites:
            MooseDocs: /MooseDocs/index.md
            Developing MOOSE Apps: docs/content/utilities/development/index.md
            Memory Logger: docs/content/utilities/memory_logger/memory_logger.md
        Help:
            Frequently Asked Questions: docs/content/help/faq.md
            INL HPC Connectivity: docs/content/help/inlhpcconnectivity.md
            Contact Us: docs/content/help/contact_us.md

Extensions:
    disable_defaults: True
    appsyntax:
        type: MooseDocs.extensions.appsyntax
        executable: ${MOOSE_DIR}/modules/combined
        includes:
            - framework/include
        remove-syntax:
            - /Variables/InitialCondition/*
            - \!/Variables/InitialCondition/AddICAction
            - /AuxVariables/InitialCondition/*
            - \!/AuxVariables/InitialCondition/AddICAction
            - /Bounds/*
            # disable: False
    globals:
        type: MooseDocs.extensions.global
        shortcuts: !include globals.yml
