# Configuration file for creating MOOSE application documentation.

# Complete YAML syntax to ignore (must include leading /). All "systems" in MOOSE matching
# these values will be completly ignored and all objects within the associated system will
# also be ignored.
hide:
    - /BCs/Periodic
    - /Bounds
    - /AuxVariables/*/InitialCondition
    - /Variables/*/InitialCondition

# The system documentation to generate.
generate:
    Framework:
        source_dir: framework
        #docs_dir: docs # default
        #build_dir: docs/documentation # default
        details_dir: docs/details
        repo: https://github.com/idaholab/moose/blob/master
        doxygen: http://mooseframework.com/docs/doxygen/moose/


       # Phase Field:
       #     yaml: phase_field.yml
       #     source:
       #         - /Users/slauae/projects/moose-doc/modules/phase_field

links:
    Tests:
        - test/tests
        - modules/phase_field/tests
    Examples:
        - examples
        - modules/phase_field/examples
    Tutorials:
        - tutorials
