# Configuration file for creating MOOSE application documentation.

repo: https://github.com/idaholab/moose

markdown:
    - /Users/slauae/projects/moose-doc/docs/details

# Complete YAML syntax to ignore (must include leading /). All "systems" in MOOSE matching
# these values will be completly ignored and all objects within the associated system will
# also be ignored.
hide:
    - /BCs/Periodic
    - /Bounds
    - /AuxVariables/*/InitialCondition
    - /Variables/*/InitialCondition

# The system documentation to generate.
generate:
    Framework:
        prefix: documentation/framework
        source:
            - /Users/slauae/projects/moose-doc/framework
       # Phase Field:
       #     yaml: phase_field.yml
       #     source:
       #         - /Users/slauae/projects/moose-doc/modules/phase_field

links:
    Tests:
        - /Users/slauae/projects/moose-doc/test/tests
        - /Users/slauae/projects/moose-doc/modules/phase_field/tests
    Examples:
        - /Users/slauae/projects/moose-doc/examples
        - /Users/slauae/projects/moose-doc/modules/phase_field/examples
    Tutorials:
        - /Users/slauae/projects/moose-doc/tutorials
