site_name: MOOSE
docs_dir: .
watch_dirs:
    - /Users/slauae/projects/moose/framework/include/kernels
extra_javascript:
    - http://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML
    - mathjaxconfig.js
markdown_extensions:
    - MooseDocs.extensions.MooseMarkdown
    - markdown_include.include
    - smarty
    - mdx_math
pages:
- Home: index.md
- Documentation: !include documentation/MooseSystems.yml
