site_name: MOOSE

site_dir: ../site

docs_dir: .

watch_dirs:
    - /Users/slauae/projects/moose-doc/framework/include/kernels

extra_javascript:
    - http://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML
    - mathjaxconfig.js

markdown_extensions:
    - markdown_include.include           # pip install markdown-include
    - mdx_math                           # pip install python-markdown-math
    - smarty

pages:
   - Home: index.md
   - Documentation:
       - Moose Flavored Markdown: markdown/MooseFlavoredMarkdown.md
       - Systems: !include gen/Systems.yml

extra:
    Source:
        Framework:
            - /Users/slauae/projects/moose-doc/framework
        Modules:
            Phase Field:
                - /Users/slauae/projects/moose-doc/modules/phase_field
    Links:
        Tests:
            - /Users/slauae/projects/moose-doc/test/tests
            - /Users/slauae/projects/moose-doc/modules/phase_field/tests
        Examples:
            - /Users/slauae/projects/moose-doc/examples
            - /Users/slauae/projects/moose-doc/modules/phase_field/examples
        Tutorials:
            - /Users/slauae/projects/moose-doc/tutorials
