site_name: MOOSE

docs_dir: .
site_dir: ../site

watch_dirs:
    - /Users/slauae/projects/moose-doc/framework/include

extra_javascript:
    - http://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML
    - mathjaxconfig.js

markdown_extensions:
    - markdown_include.include           # pip install markdown-include
    - mdx_math                           # pip install python-markdown-math
    - smarty

pages:
   - Home: index.md
   - Documentation:
       - Moose Flavored Markdown: documentation/MooseFlavoredMarkdown.md
       - Framework: !include documentation/framework/pages.yml
