site_name: MOOSE
docs_dir: .
watch_dirs:
    - /Users/slauae/projects/moose/framework/include/kernels
extra_javascript:
    - http://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML
    - mathjaxconfig.js
markdown_extensions:
   # - MooseDocs.extensions.MooseMarkdown
    - markdown_include.include           # pip install markdown-include
    - mdx_math                           # pip install python-markdown-math
    - smarty
