site_name: MOOSE
docs_dir: .
markdown_extensions:
    - MooseDocs.extensions.MooseMarkdown
    - markdown_include.include
    - smarty
    - mdx_math
extra_javascript:
    - http://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML
    - mathjaxconfig.js
