site_name: MOOSE

docs_dir: .

site_dir: ../site

extra_javascript:
    - http://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML
    - mathjaxconfig.js

markdown_extensions:
    - MooseDocs.extensions.MooseMarkdown
    - markdown_include.include           # pip install markdown-include
    - mdx_math                           # pip install python-markdown-math
    - smarty

pages:
   - Home: index.md
   - Documentation:
       - Moose Flavored Markdown: documentation/MooseFlavoredMarkdown.md
       - Framework: !include documentation/framework/pages.yml
       - Modules:
           - Phase Field: !include documentation/modules/phase_field/pages.yml
