#pylint: disable=missing-docstring
####################################################################################################
#                                    DO NOT MODIFY THIS HEADER                                     #
#                   MOOSE - Multiphysics Object Oriented Simulation Environment                    #
#                                                                                                  #
#                              (c) 2010 Battelle Energy Alliance, LLC                              #
#                                       ALL RIGHTS RESERVED                                        #
#                                                                                                  #
#                            Prepared by Battelle Energy Alliance, LLC                             #
#                               Under Contract No. DE-AC07-05ID14517                               #
#                               With the U. S. Department of Energy                                #
#                                                                                                  #
#                               See COPYRIGHT for full restrictions                                #
####################################################################################################
#pylint: enable=missing-docstring
import os
import logging

import MooseDocs
import elements

LOG = logging.getLogger(__name__)

def get_language(tag):
    """
    Helper function for extracting code highlight language from tag attributes.
    """
    # Map from lower case hljs name to latex listings name
    languages = {'c++':'C++', 'python':'Python'}
    for html, latex in languages.iteritems():
        lang = 'language-{}'.format(html)
        if lang in tag.get('class', ''):
            return latex

class MooseTable(elements.Table):
    """
    Builds table fitted to the width of the document.
    """
    def __init__(self, **kwargs):
        kwargs.setdefault('command', 'tabularx')
        super(MooseTable, self).__init__(**kwargs)
    def convert(self, tag):
        super(MooseTable, self).convert(tag)
        cols = tag.contents[0]
        frmt = ['l']*self.numColumns(tag)
        frmt[-1] = 'X'
        cols.string = ''.join(frmt)
        width = self.new()
        width['data-latex-begin'] = '{\\linewidth'
        width['data-latex-end'] = '}'
        cols.insert_before(width)

class Admonition(elements.Command):
    """
    Create an admonition in latex, assumes that the \admonition command is defined
    in the latex preamble.
    """
    def __init__(self, **kwargs):
        super(Admonition, self).__init__(name='div',
                                         command='admonition',
                                         attrs={'class':'admonition'})

    def convert(self, tag):
        super(Admonition, self).convert(tag)
        atype = tag.attrs['class'][tag.attrs['class'].index('admonition')+1]
        title = tag.find(class_='admonition-title')
        if title:
            title.replace_with(self.curly(string=title.string))
        else:
            tag.insert(0, self.curly())
        tag.p.replace_with(self.curly(string=tag.p.string))

        tag.insert(0, self.square(string='{}-title'.format(atype)))
        tag.insert(1, self.square(string=atype))
        tag['data-latex-close'] = '\n'

class MoosePreCode(elements.PreCode):
    """
    Uses listing package rather than verbatim for code.
    """
    def __init__(self, **kwargs):
        kwargs.setdefault('command', 'lstlisting')
        super(MoosePreCode, self).__init__(**kwargs)
    def convert(self, tag):
        super(MoosePreCode, self).convert(tag)
        lang = get_language(tag)
        if lang:
            sq = self.square()
            sq.append(self.new(string='language='))
            sq.append(self.new(string=lang))
            sq.attrs['data-latex-end-suffix'] = '\n'
            tag.attrs['data-latex-begin-suffix'] = ''
            tag.wrap(self.new())
            tag.insert(0, sq)


class MooseCodeDiv(MoosePreCode):
    """
    Create a listing block for code blocks generated by MooseMarkdownExtension.
    """
    def __init__(self, **kwargs):
        kwargs.setdefault('name', 'div')
        kwargs.setdefault('attrs', {'class':'moosedocs-code-div'})
        super(MooseCodeDiv, self).__init__(**kwargs)

    def convert(self, tag):
        caption = tag.contents[0].extract()
        pre = tag.pre
        super(MooseCodeDiv, self).convert(pre)

        sq = pre.find('latex', attrs={'data-latex-end-suffix':'\n'})
        if not sq:
            sq = self.square()
            pre.insert(0, sq)
            sq.attrs['data-latex-end-suffix'] = '\n'
            pre.attrs['data-latex-begin-suffix'] = ''
        else:
            sq.append(self.new(string=', '))

        sq.append(self.new(string='caption='))
        sq.append(caption)
#
#
#class moose_internal_links(elements.a):
#    """
#    Create section-based hyper links
#    """
#    def test(self, tag):
#        return super(moose_internal_links, self).test(tag) and tag['href'].startswith('#')
#
#    def convert(self, tag, content):
#        return '\\hyperref[sec:%s]{%s}' % (tag['href'][1:], content)
#
#    def preamble(self):
#        return ['\\usepackage{hyperref}']


#class moose_markdown_links(elements.a):
#    """
#    <a> tag that links to website if markdown file is provided.
#    """
#    def __init__(self, site=None):
#        self._site = site
#        self._path = None # when testing the path is determined and used in
#
#    def test(self, tag):
#        """
#        Test if the <a> tag contains a .md file include handling # for page section links.
#        """
#        if super(moose_markdown_links, self).test(tag):
#            if tag['href'].endswith('.md'):
#                self._path = tag['href'][:-3].strip('/')
#                return True
#            elif '.md#' in tag['href']:
#                self._path = tag['href'].replace('.md', '/')
#                return True
#
#        self._path = None
#        return False
#
#    def convert(self, tag, content):
#        url = '{}/{}'.format(self._site, self._path)
#        return '\\href{%s}{%s}' % (url, content)
#
#    def preamble(self):
#        return ['\\usepackage{hyperref}']

class MooseFigure(elements.Figure):
    """
    Convert moose figure block.
    """
    def __init__(self, **kwargs):
        kwargs.setdefault('name', 'div')
        kwargs.setdefault('end_prefix', '')
        super(MooseFigure, self).__init__(**kwargs)
    def test(self, tag):
        return super(MooseFigure, self).test(tag) and tag.find(class_='card') \
                                                  and tag.find(class_='card-image') \
                                                  and tag.find('img')

class MooseImage(elements.Image):
    """
    Handles images and figures created with MOOSE markdown.
    """
    def __init__(self, **kwargs):
        kwargs.setdefault('begin_suffix', '[width=\\linewidth]')
        super(MooseImage, self).__init__(**kwargs)
    def convert(self, tag):
        """
        Builds up the content of the latex figure block.
        """
        super(MooseImage, self).convert(tag)
        path = tag['src']
        if not os.path.exists(path):
            root_path = os.path.join(MooseDocs.ROOT_DIR, path)
            if os.path.exists(root_path):
                tag['src'] = root_path

class MooseCite(elements.Element):
    """
    Convert the cite command from MooseBibtex to the proper latex cite command.
    """
    def __init__(self, **kwargs):
        kwargs.setdefault('name', 'span')
        kwargs.setdefault('attrs', {'data-moose-cite': ''})
        super(MooseCite, self).__init__(**kwargs)
    def convert(self, tag):
        tag['data-latex-content'] = tag['data-moose-cite']
        super(MooseCite, self).convert(tag)

#class moose_bib(elements.ol):
#    """
#    Convert html bibliography (from MooseBibtex) to the correct latex entry.
#    """
#    attrs = ['data-moose-bibfiles']
#    def convert(self, tag, content):
#        bibfiles = eval(tag.attrs['data-moose-bibfiles'])
#        return '\\bibliographystyle{unsrtnat}\n\\bibliography{%s}' % ','.join(bibfiles)
#    def preamble(self):
#        return ['\\usepackage{natbib}']


#class moose_slider(elements.BlockElement):
#    """
#    Produces error for unsupported syntax for PDF creation.
#    """
#    name = 'div'
#    attrs = ['class']
#    def test(self, tag):
#        return super(moose_slider, self).test(tag) and 'slider' in tag.attrs['class']
#
#    def convert(self, tag, content):
#        LOG.warning("!slideshow markdown is not currently supported for latex/pdf output.")
#        return '\\admonition[error-title][error]{ERROR: Un-supported Markdown!}
#                {MOOSE Slider is not currently supported for pdf output.}'
#    def preamble(self):
#        return admonition_preamble()
#
#class moose_buildstatus(elements.BlockElement):
#    """
#    Produces error for unsupported syntax for PDF creation.
#    """
#    name = 'div'
#    attrs = ['class']
#    def test(self, tag):
#        return super(moose_buildstatus, self).test(tag) and \
#                     'moose-buildstatus' in tag.attrs['class']
#
#    def convert(self, tag, content):
#        LOG.warning("!buildstatus markdown is not currently supported for latex/pdf output.")
#        return '\\admonition[error-title][error]{ERROR: Un-supported Markdown!}
#               {MOOSE build status (!buildstatus) is not currently supported for pdf output.}'
#    def preamble(self):
#        return admonition_preamble()
#
#
#class moose_diagram(elements.BlockElement):
#    """
#    Produce and error for unsupported syntax for diagrams.
#
#    @TODO: graphviz needs to support png output, the one in the MOOSE package does not.
#    """
#    name = 'img'
#    attrs = ['class']
#    def test(self, tag):
#        return super(moose_diagram, self).test(tag) and 'moose-diagram' in tag.attrs['class']
#
#    def convert(self, tag, content):
#        LOG.warning("Dot diagram markdown syntax is not currently supported for latex/pdf output.")
#        return '\\admonition[error-title][error]
#               {ERROR: Un-supported Markdown!}{Dot diagram markdown syntax is not supported.}'
#    def preamble(self):
#        return admonition_preamble()
#
#class moose_video(elements.BlockElement):
#    """
#    Produce and error that videos are not supported.
#    """
#    name = 'video'
#    def convert(self, tag, content):
#        LOG.warning('The !video syntax is not currently supported for latex/pdf output.')
#        return '\\admonition[error-title][error]{ERROR: Un-supported Markdown!}{!video}'
#    def preamble(self):
#        return admonition_preamble()
#
